# Generated by Django 3.2.5 on 2022-01-06 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20220106_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('instituicao', models.CharField(default='Sem Instituição', max_length=255)),
                ('tipo', models.CharField(default='Corrente', max_length=255)),
                ('saldo', models.IntegerField(default=0)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dataPagamento', models.DateField()),
                ('dataPagamentoEsperado', models.DateField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='profiles.conta')),
            ],
        ),
    ]
